CART_HOST: cart.backend-{{ env }}.arunkumarnelluri.site
USER_HOST: user.backend-{{ env }}.arunkumarnelluri.site
RABBITMQ_HOST: rabbitmq-{{ env }}.arunkumarnelluri.site
RABBITMQ_USER: roboshop
RABBITMQ_PASSWORD: roboshop123